services:
  - type: web
    name: smartrag-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_NAME
        value: domainspecificrag
      - key: ALLOWED_ORIGINS
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
